dguideaton/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage import views
import homepage.urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name="main"),
    path('accounts/',include('allauth.urls')),
    path('homepage/', include('homepage.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path
from . import views

app_name ="homepage"

urlpatterns = [
    path('create/', views.create, name="create"),
    path('new_update/<int:pk>/', views.new_update, name="new_update"),
    path('detail/<int:pk>/', views.detail, name="detail"),
    path('update/<int:pk>/', views.update, name="update"),
    path('delete/<int:pk>/', views.delete, name="delete"),
    path('mylist/', views.mylist, name="mylist"),
    path('mylikes/', views.mylikes, name="mylikes"),
    path('mycomments/', views.mycomments, name="comments"),

    # like
    path('like_toggle/<int:pk>/', views.like_toggle, name="like_toggle"),

    #comments
    path('create_comment/<int:pk>/', views.create_comment, name="create_comment"),
    path('delete_comment/<int:pk>/', views.delete_comment, name="delete_comment"),

    path('delete_image/<int:pk>/', views.delete_image, name="delete_image"),

]

homepage/models.py
from django.db import models
from django.contrib.auth.models import User
from share.timestamp import TimeStampedModel
from django.utils.translation import ugettext_lazy as _

class Post(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=2000)
    content = models.TextField()
    liked_users = models.ManyToManyField(User, blank=True, related_name="liked_users", through='Like')
    image = models.FileField(upload_to='images/', null=True, blank=True)
    def __str__(self):
        return self.title
    
    def summary(self):
        return self.content[:25]

    @property
    def comments(self):
        return Comment.objects.filter(post=self)
    @property
    def likes_counts(self):
        return self.liked_users.count()
    
class Comment(TimeStampedModel):
    class Meta:
        ordering =['-created_at']
    
    users = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

    def  __str__(self):
        return self.message

class Like(TimeStampedModel):
    user = models.ForeignKey(User, verbose_name=_('작성자'), on_delete=models.CASCADE)
    post = models.ForeignKey(Post,verbose_name=_('게시글'), on_delete=models.CASCADE )

    class Meta:
        verbose_name = '게시글 좋아요'
        verbose_name_plural = '게시글 좋아요'
        unique_together = (
            ('user', 'post')
        )

homepage/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Like, Comment
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponse
import json
from django.template.loader import render_to_string

def main(request):
    posts = Post.objects.all()
    return render(request, 'main.html', {'posts':posts})

def create(request):
    user = request.user
    if user.is_anonymous:
        return redirect('account_login')

    if request.method=="POST":
        post = Post()
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.user = user
        post.image = request.FILES.get('image')
        post.save()
        return redirect('homepage:detail', post.id)
    else:
        return render(request,'homepage/create.html')

def detail(request, pk):
    posts = get_object_or_404(Post, pk=pk)
    name = str(posts.image)[7:]
    return render(request, 'homepage/detail.html', {'posts':posts, 'name':name})

def delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('main')

def new_update(request, pk):
    post = get_object_or_404(Post, pk=pk)
    name = str(post.image)[7:]
    return render(request, 'homepage/update.html', {'post':post, 'name':name})

def update(request, pk):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=pk)
        post.title = request.POST['title']
        post.content = request.POST['content']
        
        if request.FILES.get('image'):
            post.image = request.FILES.get('image')
        
        post.save()
        
        return redirect('homepage:detail', post.id)

def mylist(request):
    user = request.user
    posts = Post.objects.filter(user = user)
    return render(request, 'homepage/mylist.html', {'posts':posts})

def mylikes(request):
    user = request.user
    likes = Like.objects.filter(user = user)
    return render(request, 'homepage/mylikes.html', {'likes':likes})

def mycomments(request):
    user = request.user
    comments = Comment.objects.filter(users = user)
    return render(request, 'homepage/mycomments.html', {'comments': comments})


@require_POST
@login_required
def like_toggle(request, pk):
    post = get_object_or_404(Post, pk = pk)
    post_like, post_like_created = post.like_set.get_or_create(user=request.user)

    if not post_like_created:
        post_like.delete()
        result = "like_cancel"
    else:
        result = "like"

    context={
        'likes_counts':post.likes_counts,
        'result':result
    }
    
    return HttpResponse(json.dumps(context), content_type="application/json")

@login_required
@require_POST
def create_comment(request, pk):
    user = request.user
    if user.is_anonymous:
        return redirect('account_login')
    
    if request.method == "POST":
        post = get_object_or_404(Post, pk=pk)
        message = request.POST.get('message')
        comment = Comment.objects.create(users=user, post=post, message=message)

        return redirect('homepage:detail', post.pk )
    
    return render(request, 'main.html')

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_id = comment.post.id
    comment.delete()
    return redirect('homepage:detail', post_id)

def delete_image(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.image != None:
        post.image = None
        post.save()
    return redirect('homepage:new_update', post.pk)

homepage/templates/homepage/create.html
{% extends 'base.html' %}
{% block content %}
<div align="center" class="container" style="font-family:SDKukdetopokki-Lt;" style="margin-top:10px;">
    <br>
    <h2 style="margin-bottom:0;">아이디어 작성하기</h2>
    <div class="box" style="border-style: solid; width:70%; margin-top:5%; hegiht:50%;"   >
    <form action="{% url 'homepage:create' %}" method="POST" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <br>
        <label>아이디어 제목</label>
        <input type="text" name="title" style="width:90%;">
        <br><br>
        <label>아이디어 설명</label>
        <textarea name="content" style="width:90%;"></textarea>
        <br>
        <br>
        <div class="container" style="padding:0; margin-left:10%;">
            <input type="file" accpet="image/" name="image">
        </div>
        <br>
        <input type="submit" class="btn btn-dark" value="submit">
        <br>
        <br>
    </form>
    </div>
</div>
{% endblock %}

homepage/templates/homepage/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="width:88%;margin-left:12%; margin-right:4%;padding-left:0;font-family:SDKukdetopokki-Lt;">
    
    <div class="title" style="padding-top:3%; width:85%;">
        <h1>{{posts.title}}</h1>
    </div>

    <div align="right" class="box" style="padding-right:15%;">
        {% if user.is_authenticated %}
            <div class="alt-serv ice-item" id ="like_toggle">
                <span href="#" class="like" name ="{{posts_pk}}" value="Like">
                    {% if user in posts.liked_users.all %}
                    
                    <div class="alt-service-icon">
                        <i class="fas fa-heart" id ="like-icon"></i>
                        <!-- <button type="button" class="btn btn-success" id ="like-icon">좋아요 취소</button> -->
                    </div>
                    
                    {% else %}
                    
                    <div class="alt-service-icon">
                        <i class="far fa-heart" id ="like-icon"></i>
                        <!-- <button type="button" class="btn btn-danger" id ="like-icon">좋아요</button> -->
                    </div>
                    {% endif %}
                    
                    {% if request.user == posts.user %}
                    <span id="count-{{ posts.id }}" class="alt-services-title font-alt">
                        좋아요{{ posts.likes_counts }}개
                    </span>
                    {% endif %}
                </span>   
            </div>
        {% endif %}
        <h6>글쓴이: {{posts.user.first_name}}</h6>
    </div>
</div>
<hr width="80%">
<div class="container" style="margin-left:12%; width:88%; margin-right:4%;padding-left:0;font-family:MapoPeacefull;">
    <div>
        <h5 style="padding-right:15%;;">
            {{ posts.content | linebreaksbr }}
        </h5>
     </div>

    <div class="box" style="width:88%;">
        {% if posts.image == '' %}
            <h6>첨부파일 없음 </h6>
        {% else %}
            <span>
                <a id="id_uploaded_file" href="{{posts.image.url}}" download>{{ name }}</a>
            </span>
        {% endif %}
    </div>

    <div align="right" class="box" style="padding-right:15%;">
        {% if posts.user == request.user %}
        <button type="button" class="btn btn-outline-dark" onclick="location.href='{% url 'homepage:new_update' posts.id %}'">수정</button>
        <button type="button" class="btn btn-outline-dark" onclick="location.href='{% url 'homepage:delete' posts.id %}'">삭제</button>
        {% endif %}

        <br>
        <hr width=100%>
        <h5 style="text-align:center;"> ♪Comments♪ </h5>
        <hr width=100%>

        {% if user.is_authenticated %}
            <form action="{% url 'homepage:create_comment' posts.pk %}" method="POST" style="margin-top: 50px;" class="create-comment-form">
                {% csrf_token %}
                <div class="form-group">
                    <textarea class="form-control" name="message" id="comment-input-{{ posts.pk }}" aria-describedby="emailHelp" placeholder="댓글 달기..." required></textarea>
                </div>
                <button type="submit" class="btn btn-primary right comment-submit-button" data-post-id="{{ posts.pk }}">작성</button>
            </form><br>
        {% endif %}
        
        <br>
        <div align="left">
            <button type="submit" class="btn btn-secondary" onclick="location.href='{% url 'main' %}'">메인으로 가기</button>
        </div>    
        
        {% if posts.comments %}
        <ul class="list-group" id="comments-list-{{ posts.pk }}" style="margin-top: 40px;">
            {% for comment in posts.comments %}
                <li class="list-group-item" id="comment-{{ comment.pk }}">
                    <p style="text-align:right;">
                        <b style="font-size:medium;">작성자 : {{ comment.users.first_name }}</b>
                            {% if request.user == comment.users %}
                            <a href="{% url 'homepage:delete_comment' comment.pk %}" class="right comment-delete-button" id="comment-delete-{{ comment.pk }}" data-comment-id="{{ comment.pk }}">삭제</a>
                        {% endif %}
                    </p>
                    <p style="text-align:justify;font-size:small;">{{ comment.message | linebreaksbr }}</p>
                </li>
            {% endfor %}
        </ul>
        {% endif %}   
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
    $(".like").click(function(){
        var pk = $(this).attr('name')
        $.ajax({ // .like 버튼을 클릭하면 <새로고침> 없이 ajax로 서버와 통신하겠다.
            type: "POST", // 데이터를 전송하는 방법을 지정
            url: "{% url  'homepage:like_toggle' posts.pk %}",
            data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, // 서버로 데이터 전송시 옵션
            dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정, 없으면 알아서 판단
            // 서버측에서 전송한 Response 데이터 형식 (json)
            // {'likes_count': post.like_count, 'message': message }
            success: function(response){ // 통신 성공시 - 동적으로 좋아요 갯수 변경, 유저 목록 변경
                if (response.likes_counts == null) {
                    alert("로그인이 필요합니다.");
                    window.location.replace("/accounts/login/");
                }
                else {
                    if (response.result == "like") {
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('fas fa-heart');
                    }
                    else {
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('far fa-heart');
                    }
                    $('#count-{{ posts.id }}').html('좋아요'+response.likes_counts+'개');
                }
            },
            error: function(request, status, error){ // 통신 실패시 - 로그인 페이지 리다이렉트
            // alert("로그인이 필요합니다.")
            // +"\n"+"error:"+error)
                window.location.replace("/accounts/login/")
            //  alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
          },
        });

        // $('.comment-submit-button').click(function(e){
        //     e.preventDefault();
        //     // const createCommentButton= $(this);
        //     const postId = $(this).data('post-id');
        //     const commentMessage = $(`#comment-input-${postId}`).val();
        //     if (commentMessage === '') {
        //         alert('댓글 내용을 입력해주세요.');
        //     } else {
        //         $.ajax({
        //             url: `/homepage/create_comment/${postId}`,
        //             data: {
        //                 'csrfmiddlewaretoken': '{{ csrf_token }}',
        //                 'message': commentMessage
        //             },
        //             type: "POST",
        //             success: function(response) {
        //                 $(`#comments-list-${postId}`).prepend(response.comments);
        //                 $(`#comment-input-${postId}`).val('');
        //                 $(`#comment-delete-${response.comment_pk}`).click(function(e){
        //                     e.preventDefault();
        //                     const deleteCommentButton = $(this);
        //                     const commentId = $(this).data('comment-id');
        //                     $.ajax({
        //                         url: `/homepage/delete_comment/${commentId}/`,
        //                         data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
        //                         type: "POST",
        //                         success: function(response) {
        //                             $(`#comment-${commentId}`).remove();
        //                         },
        //                         error: function(response) {
        //                             alert('오류가 발생했습니다.');
        //                         }
        //                     })
        //                 });
        //             },
        //             error: function(response) {
        //                 alert('오류가 발생했습니다.');
        //             }
        //         });
        //     }
        // });
        //  댓글 삭제시 Ajax
        $('.comment-delete-button').click(function(e){
            e.preventDefault();
            const deleteCommentButton = $(this);
            const commentId = $(this).data('comment-id');
            $.ajax({
                url: `/homepage/delete_comment/${commentId}/`,
                data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
                type: "POST",
                success: function(response) {
                    $(`#comment-${commentId}`).remove();
                },
                error: function(response) {
                    alert('오류가 발생했습니다.');
                }
            })
        });
    })
</script>
{% endblock %}

homepage/templates/homepage/mycomments.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="width:88%;margin-left:12%; margin-right:4%;padding-left:0;font-family:SDKukdetopokki-Lt;">
    
    <div class="title" style="padding-top:3%;">
        <h2>{{  request.user.first_name }} 님이 댓글 단 목록</h2>
    </div>
</div>
<hr width="80%">

<div class="container" style="display:flex;flex-wrap:wrap; margin-left:10%; margin-right:4%;padding-left:0;padding-right:0;font-family:SDKukdetopokki-Lt;">
  {% for comment in comments %}
    <div class="card text" style="width: 18rem; margin:0 0 1% 3%;">
      <div class="card-body" >
        <b><h3 class="card-title">{{ comment.post.title }}</h3></b>
        <p style="text-align:justify;">{{ comment.post.summary }}...</p>
        <p class="text-right" style="font-size:small;">글쓴이 : {{ comment.post.user.first_name }}</p>
        <div align="right">
          <a href="{% url 'homepage:detail' comment.post.id %}" class="btn btn-dark" >보러가기</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

{% endblock %}

homepage/templates/homepage/mylikes.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="width:88%;margin-left:12%; margin-right:4%;padding-left:0;font-family:SDKukdetopokki-Lt;">
    
    <div class="title" style="padding-top:3%;">
        <h1>{{request.user.first_name}} 님이 좋아요한 목록</h1>
    </div>
</div>
<hr width="80%">
<div class="container" style="display:flex;flex-wrap:wrap; margin-left:10%; margin-right:4%;padding-left:0;padding-right:0;font-family:SDKukdetopokki-Lt;">
    {% for like in likes %}
      <div class="card text" style="width: 18rem; margin:0 0 1% 3%;">
        <div class="card-body" >
          <b><h3 class="card-title">{{ like.post.title }}</h3></b>
          <p style="text-align:justify;">{{ like.post.summary }}...</p>
          <p class="text-right" style="font-size:small;">글쓴이 : {{ like.post.user.first_name }}</p>
          <div align="right">
            <a href="{% url 'homepage:detail' like.post.id %}" class="btn btn-dark" >보러가기</a>
          </div>
        </div>
      </div>
    {% endfor %}
</div>
{% endblock %}

homepage/templates/homepage/mylist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container" style="width:88%;margin-left:12%; margin-right:4%;padding-left:0;font-family:SDKukdetopokki-Lt;">
    
    <div class="title" style="padding-top:3%;">
        <h1>{{user.first_name}} 님이 작성한 목록</h1>
    </div>
</div>
<hr width="80%">

<div class="container" style="display:flex;flex-wrap:wrap; margin-left:10%; margin-right:4%;padding-left:0;padding-right:0;font-family:SDKukdetopokki-Lt;">
  {% for post in posts %}
    <div class="card text" style="width: 18rem; margin:0 0 1% 3%;">
      <div class="card-body" >
        <b><h3 class="card-title">{{ post.title }}</h3></b>
        <p style="text-align:justify;">{{ post.summary }}...</p>
        <p class="text-right" style="font-size:small;">글쓴이 : {{ post.user.first_name }}</p>
        <div align="right">
          <a href="{% url 'homepage:detail' post.id %}" class="btn btn-dark" >보러가기</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

homepage/templates/homepage/update.html
{% extends 'base.html' %}
{% block content %}
        <div align="center" class="container" style="font-family:SDKukdetopokki-Lt;">
            <br>
            <h2 style="margin-bottom:0;">아이디어 수정하기</h2>
            <div class="box" style="border-style: solid; width:70%; margin-top:5%; hegiht:50%;" >
            <form action="{% url 'homepage:update' post.id %}" method="POST" enctype="multipart/form-data" novalidate >
                    {% csrf_token %}
                <br>
                <label>아이디어 제목</label>
                <input type="text" name="title" style="width:90%;" value="{{post.title}}">
                <br><br>
                <label>아이디어 설명</label>
                <textarea name="content" style="width:90%;">{{post.content}}</textarea>
                <br><br>
                <div class="container" style="padding:0;">
                    <h6> 수정 전 파일 : {{ name }} 
                    </h6>
                    <div class="container" style="margin-left:10%;">
                        <input type="file" name="image">
                    </div>
                    <br>
                    <h6>파일을 넣고 싶지 않을 때 -> 
                    <a href="{%url 'homepage:delete_image' post.pk %}" class="right comment-delete-button" id="comment-delete-{{ post.pk }}" data-comment-id="{{ post.pk }}">삭제</a>
                    </h6>
                </div>
                <br><br>
                <input type="submit" class="btn btn-dark" value="submit">
                <br>
                <br>
            </form>
            </div>
        </div>

<script>
    //  댓글 삭제시 Ajax
    $('.comment-delete-button').click(function(e){
            e.preventDefault();
            const deleteCommentButton = $(this);
            const commentId = $(this).data('comment-id');
            $.ajax({
                url: `/homepage/delete_image/${commentId}/`,
                data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
                type: "POST",
                success: function(response) {
                    $(`#comment-${commentId}`).remove();
                },
                error: function(response) {
                    alert('오류가 발생했습니다.');
                }
            })
        });
</script>           
{% endblock %}

homepage/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container" style="margin-top: 10px;">
    <img src="static/img/슬라이드1.JPG" alt="Responsive image" style="display:block;margin-left:auto;margin-right:auto;width:80%;">
</div>
<hr color="black" width="88%">
<div class="container" style="display:flex;flex-wrap:wrap; margin-left:10%; margin-right:4%;padding-left:0;padding-right:0;font-family:SDKukdetopokki-Lt;">
    {% for post in posts %}
      <div class="card text" style="width: 18rem; margin-left:3%; margin-bottom:1%;">
        <div class="card-body" >
          <b><h4 class="card-title">{{ post.title }}</h4></b>
          <p style="text-align:justify;">{{post.summary}}...</p>
          <p class="text-right" style="font-size:small;">글쓴이 : {{ post.user.first_name }}</p>
          <div align="right">
            <a href="{% url 'homepage:detail' post.id %}" class="btn btn-dark">보러가기</a>
          </div>
        </div>
      </div>
    {% endfor %}
</div>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko-kr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
      @font-face { font-family: 'SDKukdetopokki-Lt'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/SDKukdetopokki-aLt00.woff') format('woff'); font-weight: normal; font-style: normal; }
      @font-face { font-family: 'MapoPeacefull'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/MapoPeacefullA.woff') format('woff'); font-weight: normal; font-style: normal; }
    </style>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
  
    <title>DLIT</title>
  </head>

  <body>
    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}
    <br><br>

    {% include 'footer.html' %}
    <!-- {% include 'footer.html' %} -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  </body>
</html>

templates/footer.html
{% load static %}
<footer class="page-section bg-gray-lighter footer pb-60" > 
    <div class="footer" style="position:absolute;color:white; font-family:MapoPeacefull;background-color: #3d3d3d; text-align:right;margin-bottom:0;width:100%;" >
        <span class="f-right" style="margin-right:10%;">
            <h1>DLIT</h1>
            <h6>문의는 카톡으로 주세요.<br>
            <span>Made by dgulion</span>
            </h6>
        </span>
    </div>
</footer>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light" style="font-family:SDKukdetopokki-Lt; margin-top:2%;margin-left:10%;margin-right:10%;">
    <a class="navbar-brand" href="{% url 'main' %}"><h1>DLIT</h1></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav col" style="text-align:center;">
            {% if request.user.is_authenticated %}
                <li class="nav-item" style="font-family:SDKukdetopokki-Lt;">
                    <p><a class="nav-link" href="{% url 'homepage:mylist' %}"><h5>나의 목록</h5></a></p>
                </li>
                <li class="nav-item" style="font-family:SDKukdetopokki-Lt;">
                    <p><a class="nav-link" href="{% url 'homepage:mylikes' %}"><h5>나의 좋아요</h5></a></p> 
                </li>
                <li class="nav-item">
                    <p><a class = "nav-link" href="{% url 'homepage:comments' %}"><h5>나의 댓글</h5></a></p>
                </li>
                <li class="nav-item">
                    <p><a class="nav-link" href="{% url 'homepage:create' %}"><h5>작성하기</h5></a></p>
                </li>
                <li class="nav-item">
                    <p><a class = "nav-link" href="{% url 'account_logout'%}"><h5>로그아웃</h5></a></p>
                </li>
            {% else %}
                <li class="nav-item">
                    <p><a  class="nav-link" href="{% url 'account_login' %}" >로그인</a></p>
                </li>

            {% endif %}
        </ul>
    </div>
</nav>
<hr color="black" width="88%" style="margin-top:0px;">